version: '3.7'

services:
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    image: nginx
    volumes:
      - ${APP_FOLDER}:/var/www/html:cached
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:cached
    depends_on:
      - php
    networks:
      - backend
      - web
    # ports:
    #   - 82:80
    labels:
      #### Labels define the behavior and rules of the traefik proxy for this container ####
      - "traefik.enable=true" # <== Enable traefik to proxy this container
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.rule=Host(`${URL}`)" # <== Your Domain Name goes here for the http rule
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.entrypoints=http" # <== Defining the entrypoint for http, **ref: line 30
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.middlewares=redirect@file" # <== This is a middleware to redirect to https
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.rule=Host(`${URL}`)" # <== Your Domain Name for the https rule
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.entrypoints=https" # <== Defining entrypoint for https, **ref: line 31
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.tls.certresolver=mytlschallenge"
      # - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-secured.tls.certresolver=mytlschallenge" # <== Defining certsresolvers for https
      # - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.tls=true"


  php:
    container_name: ${COMPOSE_PROJECT_NAME}-php
    build: ./
    volumes:
      - ${APP_FOLDER}:/var/www/html:cached
      - ./php.conf:/usr/local/etc/php-fpm.d/www.conf:cached
    networks:
      - backend
      - db
    env_file:
      - .env
    labels:
      - "traefik.enable=false"

networks:
  web:
    external: true
  backend:
    external: false
  db:
    external: true
